config/routes.rb
Rails.application.routes.draw do
  resources :cocktails do
    resources :doses, shallow: true
    # resources :doses, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :cocktail, uniqueness: { scope: :ingredient }
  validates :description, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :doses
  validates :name, presence: true, uniqueness: true
  validates_associated :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    query = params[:query]
    if query == nil || query.blank?
      @cocktails = Cocktail.all
    else
      @cocktails = Cocktail.where(name: params[:query])
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @ingredient = Ingredient.find(dose_params[:ingredient_id])
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(description: dose_params[:description])
    @dose.cocktail = @cocktail
    @dose.ingredient = @ingredient
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'new'
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktails_path
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="height: 50px;margin-bottom: 20px;">
<%= simple_form_for :search, url: cocktails_path, method: :get do |f| %>
  <div class="search-form-control form-group">
    <input class="form-control string required" type="text" name="query" id="search_query" />
    <button name="button" type="submit" class="btn btn-flat">
      <i class="fas fa-search"></i> Search
    </button>
  </div>
<% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>
<div>
<div class="container" style="height: 300px;width: 500px;margin-bottom: 20px"><div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="https://cdn.pixabay.com/photo/2015/08/25/16/12/lime-907124_1280.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://cdn.pixabay.com/photo/2016/07/21/11/17/mineral-water-1532300_960_720.jpg" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="https://as2.ftcdn.net/jpg/00/08/16/43/500_F_8164333_U6FdhipSwvcqSa8DdoKYv1HleNyDyTWI.jpg" class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</div>


<div class="container d-flex" >
  <div class="row" style="justify-content: space-around;">
  <% @cocktails.each do |cocktail| %>
  <div class="card-category col-sm-6 col-md-3 col-xs-12" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg);margin: 10px;">
  <p><%= cocktail.name %></p>
  <br>
<!--   <%= link_to cocktail.name, cocktail_path(cocktail) %> -->
</div>
  <!-- <div class="card col-xs-12 m-3 col-sm-6 col-md-3">
  <img src="" class="card-img-top" alt="...">
  <div class="card-body" style="height: 100%;">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">gggggg</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
  <li><%= link_to cocktail.name, cocktail_path(cocktail) %></li>
</div> -->

  <% end %>

  </div>
</div>

<div style="align-items: center;display: flex;justify-content: center;">
  <button type="button" class="btn btn-primary btn-lg btn-block" style="color: black;width: 300px;"><%=link_to 'Add a new cocktail', new_cocktail_path, style: 'color: black' %></button>
</div>


</div>

      <!-- <div class="col-xs-12 col-sm-6 col-md-3"> -->
 <!--  <div class="card col-sm-3 m-3" style="width: 250px;"> -->

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h1>Create a new cocktail</h1>


<%= simple_form_for @cocktail do |f| %>
  <%= f.input :name %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
   </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h1><%= @cocktail.name %></h1>
<%= simple_form_for @cocktail do |f| %>
  <%= f.association :ingredients %>
  <%= f.association :doses, label_method: :description %>
<% end %>

<button type="button" class="btn btn-secondary"><%= link_to 'Go back', cocktails_path %></button>
<button type="button" class="btn btn-success"><%= link_to 'Add new doses', new_cocktail_dose_path(@cocktail) %></button>

<% @cocktail.doses.each do |dose| %>
  <p>Here's a dose: (...)<p>

  <button type="button" class="btn btn-danger"><%= link_to 'Delete the dose', dose_path(dose), method: :delete %></button>

<% end %>

app/views/doses/create.html.erb
<h1>Doses#create</h1>
<p>Find me in app/views/doses/create.html.erb</p>

app/views/doses/destroy.html.erb
<h1>Doses#destroy</h1>
<p>Find me in app/views/doses/destroy.html.erb</p>

app/views/doses/new.html.erb
<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.association :ingredient %>
  <%= f.input :description %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

<%= link_to "Go back", cocktails_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>
  </body>
</html>